version: "3"
services:
  back:
    image: backavtomat:latest


  bd:
    image: postgres:latest
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432


  gateway:
    image: nginx:latest
    ports:
      - 8085:8085
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./front/dist:/usr/share/nginx/www