version: "3"
services:
  back:
    build: ./back

  gateway:
    image: nginx:latest
    ports:
      - 8085:8085
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../front/dist:/usr/share/nginx/www